//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories_
    {
        public Categories_()
        {
            this.Subcategories_ = new HashSet<Subcategories_>();
        }
    
        public double CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<Subcategories_> Subcategories_ { get; set; }
    }
}
