//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_
    {
        public Users_()
        {
            this.Orders_ = new HashSet<Orders_>();
        }
    
        public double UserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string Login { get; set; }
        public Nullable<double> RoleID { get; set; }
    
        public virtual ICollection<Orders_> Orders_ { get; set; }
        public virtual Roles_ Roles_ { get; set; }
    }
}
