//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers_
    {
        public Manufacturers_()
        {
            this.Products_ = new HashSet<Products_>();
        }
    
        public double ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
    
        public virtual ICollection<Products_> Products_ { get; set; }
    }
}
