//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_for_importEntities : DbContext
    {
        public db_for_importEntities()
            : base("name=db_for_importEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories_> Categories_ { get; set; }
        public DbSet<Manufacturers_> Manufacturers_ { get; set; }
        public DbSet<OrderItems_> OrderItems_ { get; set; }
        public DbSet<Orders_> Orders_ { get; set; }
        public DbSet<Products_> Products_ { get; set; }
        public DbSet<Roles_> Roles_ { get; set; }
        public DbSet<Sizes_> Sizes_ { get; set; }
        public DbSet<StockItems_> StockItems_ { get; set; }
        public DbSet<Subcategories_> Subcategories_ { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users_> Users_ { get; set; }
    }
}
