//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_
    {
        public Orders_()
        {
            this.OrderItems_ = new HashSet<OrderItems_>();
        }
    
        public double OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> UserID { get; set; }
    
        public virtual ICollection<OrderItems_> OrderItems_ { get; set; }
        public virtual Users_ Users_ { get; set; }
    }
}
