//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems_
    {
        public double OrderItemID { get; set; }
        public Nullable<double> OrderID { get; set; }
        public Nullable<double> StockItemID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual Orders_ Orders_ { get; set; }
        public virtual StockItems_ StockItems_ { get; set; }
    }
}
