//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_
    {
        public Products_()
        {
            this.StockItems_ = new HashSet<StockItems_>();
        }
    
        public double ProductID { get; set; }
        public Nullable<double> SubcategoryID { get; set; }
        public Nullable<double> ManufacturerID { get; set; }
        public string ProductName { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public string Composition { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
    
        public virtual Manufacturers_ Manufacturers_ { get; set; }
        public virtual Subcategories_ Subcategories_ { get; set; }
        public virtual ICollection<StockItems_> StockItems_ { get; set; }
    }
}
