//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_
    {
        public Roles_()
        {
            this.Users_ = new HashSet<Users_>();
        }
    
        public double RoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Users_> Users_ { get; set; }
    }
}
