//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizes_
    {
        public Sizes_()
        {
            this.StockItems_ = new HashSet<StockItems_>();
        }
    
        public double SizeID { get; set; }
        public Nullable<double> SizeValue { get; set; }
    
        public virtual ICollection<StockItems_> StockItems_ { get; set; }
    }
}
