//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItems_
    {
        public StockItems_()
        {
            this.OrderItems_ = new HashSet<OrderItems_>();
        }
    
        public double StockItemID { get; set; }
        public Nullable<double> ProductID { get; set; }
        public Nullable<double> SizeID { get; set; }
        public Nullable<double> AvailableQuantity { get; set; }
    
        public virtual ICollection<OrderItems_> OrderItems_ { get; set; }
        public virtual Products_ Products_ { get; set; }
        public virtual Sizes_ Sizes_ { get; set; }
    }
}
