//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategories_
    {
        public Subcategories_()
        {
            this.Products_ = new HashSet<Products_>();
        }
    
        public double SubcategoryID { get; set; }
        public Nullable<double> CategoryID { get; set; }
        public string SubcategoryName { get; set; }
    
        public virtual Categories_ Categories_ { get; set; }
        public virtual ICollection<Products_> Products_ { get; set; }
    }
}
