//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfishaSit
    {
        public int ID { get; set; }
        public Nullable<int> SitID { get; set; }
        public Nullable<int> AfishaID { get; set; }
        public Nullable<bool> isTaken { get; set; }
    
        public virtual Afisha Afisha { get; set; }
        public virtual Sit Sit { get; set; }
    }
}
