//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmSearchEntities1 : DbContext
    {
        public FilmSearchEntities1()
            : base("name=FilmSearchEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afisha> Afisha { get; set; }
        public virtual DbSet<AfishaSit> AfishaSit { get; set; }
        public virtual DbSet<AgeLimit> AgeLimit { get; set; }
        public virtual DbSet<CinemaHallType> CinemaHallType { get; set; }
        public virtual DbSet<FilmGenres> FilmGenres { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Sit> Sit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
