//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutAndKing.DB_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public string Reason { get; set; }
        public Nullable<int> AuthorID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual UserReviews UserReviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
