//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutAndKing.DB_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KIP_ReadWriteAndTakeYourTimeEntities : DbContext
    {
        public KIP_ReadWriteAndTakeYourTimeEntities()
            : base("name=KIP_ReadWriteAndTakeYourTimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorApplication> AuthorApplication { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<DefrostingApplication> DefrostingApplication { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ReadingListSection> ReadingListSection { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserReadingList> UserReadingList { get; set; }
        public virtual DbSet<UserReviews> UserReviews { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
