//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutAndKing.DB_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReadingList
    {
        public int UserID { get; set; }
        public int BookID { get; set; }
        public int SectionID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ReadingListSection ReadingListSection { get; set; }
        public virtual Users Users { get; set; }
    }
}
