//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nail_nail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int MasterID { get; set; }
        public int ServiceTypeID { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public decimal TotalPrice { get; set; }
        public string PaymentMethod { get; set; }
        public string Comment { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
