//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financial_operations
    {
        public int ID { get; set; }
        public Nullable<bool> OperationType { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<int> DetailID { get; set; }
    
        public virtual Storage Storage { get; set; }
    }
}
