//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class likeNaGeev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public likeNaGeev()
        {
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
        public int ID { get; set; }
        public string ClothName { get; set; }
        public string ClothSize { get; set; }
        public string ClothType { get; set; }
        public string ClothSex { get; set; }
        public double ClothPrice { get; set; }
        public Nullable<int> ClothCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
