//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Solodov_NagievOrderEntities1 : DbContext
    {
        public Solodov_NagievOrderEntities1()
            : base("name=Solodov_NagievOrderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<likeNaGeev> likeNaGeev { get; set; }
        public virtual DbSet<OrdersHistory> OrdersHistory { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
    }
}
