//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarServiceBD_Solodov123Entities : DbContext
    {
        public CarServiceBD_Solodov123Entities()
            : base("name=CarServiceBD_Solodov123Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balance { get; set; }
        public virtual DbSet<Financial_operations> Financial_operations { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
    }
}
