//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersHistory
    {
        public int ID { get; set; }
        public Nullable<int> ID_ShoppingCart { get; set; }
        public Nullable<decimal> PriceSum { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
