//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ID { get; set; }
        public int id_Сlient { get; set; }
        public int id_Cloth { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual likeNaGeev likeNaGeev { get; set; }
    }
}
